#!/usr/bin/env php
<?php

defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('YII_DEBUG') or define('YII_DEBUG',true);

require_once dirname(__FILE__) . '/vendor/autoload.php';
$config    = dirname(__FILE__) . '/config/console.php';

$app = Yii::createConsoleApplication($config);
$app->commandRunner->addCommands(YII_PATH . '/cli/commands');
$app->run();